; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; https://docs.platformio.org/en/latest/platforms/espressif32.html

[platformio]
src_dir = src/src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = src/partitions.csv
monitor_raw = yes
monitor_echo = yes
monitor_eol = LF
upload_speed = 921600
build_type = debug

extra_scripts =
    pre:src/extra_script.py
    pre:src/prepare_data_folder.py

build_flags =
    -D DEFAULT_SSID=\"simple-fpv-timer-00\"
    -I src/components/led_strip/include
    -I src/components/led_strip/interface
#    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE
#    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
